#!/bin/bash

username=`whoami`
timestamp=`date +%Y.%m.%d_%H:%M:%S`
dir=`pwd`
dir_name=${dir##*/}
dir_tral=${dir_name#*n}

echo "shell Run!";
echo "pam: $0";
echo "pam: $1";
echo "pam: $2";

rm -rf .start.vcs_sim.$1  vcs_sim.$1

make vcs_sim.$1$2 TC=$1  \
UVM_TEST=$2 \
ENABLE_UVM=1 \
VCS_BUILD_NAME=uvm_chip \
WORK_DIR=$dir/../work$dir_tral
