#!/bin/bash

#Fname=$(cd 'dirname $0';pwd)
fpath=$(pwd)
fname=${fpath##*/}
echo ${fname}


echo "shell Run!";
echo "pam: $0";
echo "pam: $1";
echo "pam: $2";

hexclt="_clt"
hexsvr="_svr"

rm  $fname$hexclt.bin
rm  $fname$hexclt*

rm  $fname$hexsvr.bin
rm  $fname$hexsvr*


cat  /home/upload_data/songxiaowei/BR003_BR_LMS.bin  > ./${fname}${hexclt}.bin
cat  /home/upload_data/songxiaowei/BR003_BR_LMM.bin  > ./${fname}${hexsvr}.bin

python ./DBhex.py $fname$hexclt.bin
python ./DBhex.py $fname$hexsvr.bin
